#!/usr/bin/env bash
# BookHero start up script
# Coded by Werner Gillmer <werner.gillmer@gmail.com>


function firstTime
{
	echo "Setting up BookHero for the first time."
	bundle install
	rake db:reset
	rake db:migrate
	exit 0
}

function startBookHero
{
	echo -n "Starting BookHero..."
	unicorn_rails -p 9911 -D
	echo "done"
	echo "BookHero running on http://0.0.0.0:9911"
}

function stopBookHero
{
	echo -n "Stopping BookHero..."
	if [ -f tmp/pids/unicorn.pid ]; then
	  UNICORN_PID=`cat tmp/pids/unicorn.pid`
	  kill $UNICORN_PID
	  echo "done"
	else
		echo "BookHero does not seem to be running"
		exit 1
	fi
}


case "$1" in
	--firsttime) firstTime "1" ;;
    --start) startBookHero "2" ;;
    --stop) stopBookHero ;; 
    *) echo "Usage : "
       echo "    --firsttime (Run this the first time your setting up BookHero)"
       echo "    --start (Start up BookHero)"
       echo "    --stop (Stop BookHero)"
     ;;
esac
