#!/usr/bin/env bash
# BookHero start up script
# Coded by Werner Gillmer <werner.gillmer@gmail.com>


function firstTime
{
	echo "Setting up BookHero for the first time."
	bundle install
	rake db:reset
	rake db:migrate
	exit 0
}

function startBookHero
{
	echo -n "Starting BookHero..."
	unicorn_rails -p 9911 -D
	echo "done"
}

function stopBookHero
{
	echo -n "Stopping BookHero..."
	ps aux | grep unicorn | grep master | grep 9911 | cut -d" " -f4 | xargs kill
	echo "done"
}


case "$1" in
	--firsttime) firstTime "1" ;;
    --start) startBookHero "2" ;;
    --stop) stopBookHero ;; 
    *) echo "Usage : "
       echo "    --firstime (Run this the first time your setting up BookHero)"
       echo "    --start (Start up BookHero)"
       echo "    --stop (Stop BookHero)"
     ;;
esac
